### PR TITLE
fix: add force object to automation config replicaset object

### LINKED ISSUE #130: Missing Force property from opsmngr.AutomationConfig.ReplicaSets
**Describe the bug**

Missing `replicaSets[n].force`  property in the replicaset automation config for opsmngr.

**Expected behavior**
`opsmngr.AutomationConfig.ReplicaSets[*].Force` to exist.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Irrelevant but
 - OS: macOS
 - Lib Version: master
 - Product: OpsManager

### PR DESCRIPTION
**Pull request by mpilar**
## Proposed changes

Adds Force property to `opsmngr.AutomationConfig.ReplicaSets`

Closes #130 

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added any necessary documentation (if appropriate)
- [X] I have run `make fmt` and formatted my code

## Further comments

Simple change to add a parameter to existing structures used for API calls.

### CODE REVIEW

File: opsmngr/automation_config.go [hunk 1]
```diff
@@ -236,6 +236,11 @@ type ReplicaSet struct {
 	Members                            []Member                `json:"members"`
 	Settings                           *map[string]interface{} `json:"settings,omitempty"`
 	WriteConcernMajorityJournalDefault string                  `json:"writeConcernMajorityJournalDefault,omitempty"`
+	Force                              Force                   `json:"force,omitempty"`
```
Comment (gssbzn) [inline opsmngr/automation_config.go:239]: [q] do we need to make this a pointer so it can be null?
```suggestion
	Force                              *Force                   `json:"force,omitempty"`
```

File: opsmngr/automation_config.go [hunk 2]
```diff
@@ -236,6 +236,11 @@ type ReplicaSet struct {
...
+}
+
+type Force struct {
+	CurrentVersion int `json:"currentVersion,omitempty"`
```
Comment (gssbzn) [inline opsmngr/automation_config.go:243]: [q] can this be zero(0)? if yes either remove `omitempty` or make it a pointer

**Review by gssbzn — APPROVED** [review]

**Comment by gssbzn** [comment]
Thanks for the contribution @mpilar, it seems you still have not signed our CLA, or at least not with your github user name. I'll merge this as soon as I confirm you have signed the CLA

**Comment by mpilar** [comment]
> Thanks for the contribution @mpilar, it seems you still have not signed our CLA, or at least not with your github user name. I'll merge this as soon as I confirm you have signed the CLA

Done @gssbzn
